### ISSUE TITLE
Allow set X-Frame-Options directive

### ISSUE THREAD

**Issue by jhernandis** [aidantwoods/SecureHeaders#16]
Is usual to use an iframe to show content from facebook stream, or twitter, for set an examples.

I think a directive of ->csp(), some like
`$headers->csp('frame', 'sameorigin');`
`$headers->csp('frame', ['sameorigin', 'http://www.facebook.com']);`

Thanks for consider.

**Comment by aidantwoods** [comment]
Hey, the directive you're looking for is [`child-src`](https://www.w3.org/TR/CSP2/#directive-child-src), (and might as well duplicate the policy to [`frame-src`](https://www.w3.org/TR/CSP3/#directive-frame-src) too – which is being 'undeprecated' in the upcoming CSP3).

I considered making a [friendly source](https://github.com/aidantwoods/SecureHeaders/wiki/friendly_directives_and_sources) name for it, but figured it might become amiguous with [`frame-ancestors`](https://www.w3.org/TR/CSP2/#directive-frame-ancestors). This coincidently is the CSP `X-Frame-Options` equivalent. 

`X-Frame-Options` and `frame-ancestors` both govern which domains may frame *your* site – rather than what it appear you're looking to do (frame another origin).

Just as a side note – if you do want to set `X-Frame-Options`, SecureHeaders will auto set it to `Deny` via a [header proposal](https://github.com/aidantwoods/SecureHeaders/wiki/header-proposals). But as with these header proposals, you override that default by either [explicitly removing it](https://github.com/aidantwoods/SecureHeaders/wiki/removeHeader), or just [setting it to the desired value](https://github.com/aidantwoods/SecureHeaders/wiki/header) yourself.

**Comment by jhernandis** [comment]
A lot of thanks. I'll set the value.

That's a great piece of software.

**Comment by aidantwoods** [comment]
@jhernandis awesome, and thanks! 😄
